/**
 * Companies House identity service
 * Companies House identity and authentication service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.wso2.client.model.CompaniesHouseIdentityService;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserProfile {
  
  @SerializedName("email")
  private String email = null;
  @SerializedName("forename")
  private String forename = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("locale")
  private String locale = null;
  @SerializedName("surname")
  private String surname = null;

  /**
   * The users email address
   **/
  @ApiModelProperty(value = "The users email address")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * The users forename
   **/
  @ApiModelProperty(value = "The users forename")
  public String getForename() {
    return forename;
  }
  public void setForename(String forename) {
    this.forename = forename;
  }

  /**
   * The users unique ID
   **/
  @ApiModelProperty(required = true, value = "The users unique ID")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The users chosen locale
   **/
  @ApiModelProperty(value = "The users chosen locale")
  public String getLocale() {
    return locale;
  }
  public void setLocale(String locale) {
    this.locale = locale;
  }

  /**
   * The users surname
   **/
  @ApiModelProperty(value = "The users surname")
  public String getSurname() {
    return surname;
  }
  public void setSurname(String surname) {
    this.surname = surname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfile userProfile = (UserProfile) o;
    return (this.email == null ? userProfile.email == null : this.email.equals(userProfile.email)) &&
        (this.forename == null ? userProfile.forename == null : this.forename.equals(userProfile.forename)) &&
        (this.id == null ? userProfile.id == null : this.id.equals(userProfile.id)) &&
        (this.locale == null ? userProfile.locale == null : this.locale.equals(userProfile.locale)) &&
        (this.surname == null ? userProfile.surname == null : this.surname.equals(userProfile.surname));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.forename == null ? 0: this.forename.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.locale == null ? 0: this.locale.hashCode());
    result = 31 * result + (this.surname == null ? 0: this.surname.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfile {\n");
    
    sb.append("  email: ").append(email).append("\n");
    sb.append("  forename: ").append(forename).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  locale: ").append(locale).append("\n");
    sb.append("  surname: ").append(surname).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
